coverage:
  status:
    project:
      default:
        if_ci_failed: success
    patch: off
flag_management:
  api:
    carryforward: true
    paths:
      - api
  worker:
    carryforward: true
    paths:
      - worker
comment: false