coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 5%
    patch: off
flag_management:
  api:
    carryforward: true
    paths:
      - api
  worker:
    carryforward: true
    paths:
      - worker
comment: false