version: '3'
services:
  # applications
  api:
    build: api
    restart: always
    container_name: api
    ports:
      - '5001:5001'
      - '15001:15001'
    depends_on:
      - database
      - worker
    environment:
      PENSIEVE_DATABASE_HOST: database
      PENSIEVE_DATABASE_PORT: 5432
      PENSIEVE_DATABASE_USERNAME: pensieve
      PENSIEVE_DATABASE_PASSWORD: pensieve
      PENSIEVE_DATABASE_NAME: pensieve
      PENSIEVE_WORKER_HOST: worker
      PENSIEVE_WORKER_PORT: 15002
      PENSIEVE_LOG_LEVEL: DEBUG
  worker:
    build: worker
    restart: always
    container_name: worker
    ports:
      - '15002:15002'
    environment:
      PENSIEVE_API_HOST: api
      PENSIEVE_API_PORT: 15001
      PENSIEVE_LOG_LEVEL: DEBUG
    volumes:
      - ./storage:/storage:rw
  # infra services
  database:
    image: postgres:15
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: pensieve
      POSTGRES_PASSWORD: pensieve
    ports:
      - '5432:5432'
    volumes:
      - ./infra/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql