services:
  # applications
  api:
    container_name: api
    build: api
    restart: always
    ports:
      - "5001:5001"
      - "15001:15001"
    depends_on:
      - database
      - cache
    environment:
      SMRITI_WORKER_HOST: worker
      SMRITI_CACHE_TYPE: redis
      SMRITI_STORAGE_PROVIDER: disk
    volumes:
      - ./storage:/storage:rw
  worker:
    container_name: worker
    build:
      context: ./worker
      dockerfile: Dockerfile
      additional_contexts:
        shared_protos: protos
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - api
    environment:
      SMRITI_API_HOST: api
      SMRITI_API_PORT: 15001
      SMRITI_MODELS_DIR: /models
    volumes:
      - ./storage:/storage:rw
      - ./models:/models:rw
  database:
    container_name: database
    image: pgvector/pgvector:0.8.2-pg18
    restart: always
    environment:
      POSTGRES_USER: smritiuser
      POSTGRES_PASSWORD: smritipass
      POSTGRES_DB: smriti
    ports:
      - "5432:5432"
  cache:
    container_name: cache
    image: redis:8.8.0-alpine
    restart: always
    command: >
      --requirepass smritipass
    ports:
      - "6379:6379"
