version: '3'
services:
  # applications
  api:
    container_name: api
    build: api
    restart: always
    ports:
      - '5001:5001'
      - '15001:15001'
    depends_on:
      - database
    environment:
      SMRITI_WORKER_HOST: worker
      SMRITI_LOG_LEVEL: DEBUG
      SMRITI_DATABASE_LOG_LEVEL: INFO
      SMRITI_CACHE_TYPE: redis
    volumes:
      - ./storage:/storage:rw
  worker:
    container_name: worker
    build: worker
    restart: always
    ports:
      - '15002:15002'
    depends_on:
      - api
    environment:
      SMRITI_API_HOST: api
      SMRITI_LOG_LEVEL: DEBUG
    volumes:
      - ./storage:/storage:rw
  # infra services
  database:
    container_name: database
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smriti
      POSTGRES_PASSWORD: smriti
    ports:
      - '5432:5432'
  cache:
    container_name: cache
    image: redis:7.0-alpine
    restart: always
    command: >
      --requirepass smriti
    ports:
      - '6379:6379'