version: '3'
services:
  # applications
  api:
    container_name: api
    build: api
    restart: always
    ports:
      - '5001:5001'
      - '15001:15001'
    depends_on:
      - database
      - cache
      - storage
    environment:
      SMRITI_WORKER_HOST: worker
      SMRITI_CACHE_TYPE: redis
      SMRITI_STORAGE_PROVIDER: disk
      SMRITI_STORAGE_ENDPOINT: storage:9000
      SMRITI_STORAGE_ACCESS_KEY: smritiuser
      SMRITI_STORAGE_SECRET_KEY: smritipass
    volumes:
      - ./storage:/storage:rw
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.2'
    #       memory: 256M
  worker:
    container_name: worker
    build: worker
    restart: always
    ports:
      - '5002:5002'
      - '15002:15002'
    depends_on:
      - api
    environment:
      SMRITI_API_HOST: api
      PYTHONUNBUFFERED: '1'
      TOKENIZERS_PARALLELISM: false
    volumes:
      - ./storage:/storage:rw
      - ./models:/models:rw
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.2'
    #       memory: 3G
  # infra services
  database:
    container_name: database
    image: pgvector/pgvector:0.7.2-pg16
    restart: always
    environment:
      POSTGRES_USER: smritiuser
      POSTGRES_PASSWORD: smritipass
      POSTGRES_DB: smriti
    ports:
      - '5432:5432'
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.2'
    #       memory: 256M
  cache:
    container_name: cache
    image: redis:7.2.5-alpine
    restart: always
    command: >
      --requirepass smritipass
    ports:
      - '6379:6379'
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.2'
    #       memory: 256M
  storage:
    container_name: storage
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    volumes:
      - ./storage:/storage
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: smritiuser
      MINIO_ROOT_PASSWORD: smritipass
    command: server --address 0.0.0.0:9000 /storage
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.2'
    #       memory: 256M