version: '3'
services:
  # applications
  api:
    image: smritihq/api:master
    ports:
      - '5001:5001'
      - '15001:15001'
    depends_on:
      - database
    environment:
      SMRITI_WORKER_HOST: worker
      SMRITI_LOG_LEVEL: DEBUG
      SMRITI_DATABASE_LOG_LEVEL: INFO
      SMRITI_CACHE_TYPE: redis
      SMRITI_STORAGE_PROVIDER: minio
      SMRITI_STORAGE_ENDPOINT: storage:9000
      SMRITI_STORAGE_ACCESS_KEY: smritiuser
      SMRITI_STORAGE_SECRET_KEY: smritipass
    volumes:
      - ./storage:/storage:rw
  worker:
    image: smritihq/worker:master
    ports:
      - '15002:15002'
    environment:
      SMRITI_API_HOST: api
      SMRITI_LOG_LEVEL: DEBUG
    volumes:
      - ./storage:/storage:rw
    deploy:
      replicas: 2
  # infra services
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: smritiuser
      POSTGRES_PASSWORD: smritipass
    ports:
      - '5432:5432'
  cache:
    image: redis:7.0-alpine
    command: >
      --requirepass smriti
    ports:
      - '6379:6379'
  storage:
    container_name: storage
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    volumes:
      - ./storage:/storage
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: smritiuser
      MINIO_ROOT_PASSWORD: smritipass
    command: server --address 0.0.0.0:9000 /storage
    restart: always