version: "3"
services:
  # applications
  api:
    image: smritihq/api:master
    ports:
      - "5001:5001"
      - "15001:15001"
    depends_on:
      - database
    environment:
      SMRITI_WORKER_HOST: worker
      SMRITI_LOG_LEVEL: DEBUG
      SMRITI_DATABASE_LOG_LEVEL: INFO
      SMRITI_CACHE_TYPE: redis
      SMRITI_STORAGE_PROVIDER: minio
      SMRITI_STORAGE_ENDPOINT: storage:9000
      SMRITI_STORAGE_ACCESS_KEY: smritiuser
      SMRITI_STORAGE_SECRET_KEY: smritipass
    volumes:
      - ./storage:/storage:rw
  worker:
    image: smritihq/pyworker:master
    ports:
      - "15002:15002"
    environment:
      SMRITI_API_HOST: api
      SMRITI_API_PORT: 15001
      SMRITI_LOG_LEVEL: DEBUG
    volumes:
      - ./storage:/storage:rw
    deploy:
      replicas: 2
  # infra services
  database:
    image: pgvector/pgvector:0.8.2-pg18
    restart: always
    environment:
      POSTGRES_USER: smritiuser
      POSTGRES_PASSWORD: smritipass
      POSTGRES_DB: smriti
    ports:
      - "5432:5432"
  cache:
    image: redis:8.8.0-alpine
    command: >
      --requirepass smriti
    ports:
      - "6379:6379"
  storage:
    container_name: storage
    image: dxflrs/garage:v2.3.0
    volumes:
      - ./storage/data:/var/lib/garage/data
      - ./storage/meta:/var/lib/garage/meta
      - ./storage/garage.toml:/etc/garage.toml:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
