version: '3'
services:
  # applications
  api:
    image: carouselhq/api:master
    ports:
      - '5001:5001'
      - '15001:15001'
    depends_on:
      - database
    environment:
      CAROUSEL_WORKER_HOST: worker
      CAROUSEL_LOG_LEVEL: DEBUG
      CAROUSEL_DATABASE_LOG_LEVEL: INFO
    volumes:
      - ./storage:/storage:rw
  worker:
    image: carouselhq/worker:master
    ports:
      - '15002:15002'
    environment:
      CAROUSEL_API_HOST: api
      CAROUSEL_LOG_LEVEL: DEBUG
    volumes:
      - ./storage:/storage:rw
    deploy:
      replicas: 2
  # infra services
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: carousel
      POSTGRES_PASSWORD: carousel
    ports:
      - '5432:5432'
    volumes:
      - ./infra/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql