setup:
	@echo "[setup]: Installing requirements..."; \
		pip install -r requirements.txt; \
		echo "[setup]: Installing drivers..."
test-all:
	@echo "Testing all scenarios"
test-mediaitems:
	@echo "Testing feature: mediaitems"
test-albums:
	@echo "Testing feature: albums"
test-library:
	@echo "Testing feature: library"
test-explore:
	@echo "Testing feature: explore"
test-search:
	@echo "Testing feature: search"