include(FetchContent)
set(FETCHCONTENT_BASE_DIR ${CMAKE_SOURCE_DIR}/third_party)
function(fetch_dependency name repo tag)
    FetchContent_Declare(
        ${name}
        GIT_REPOSITORY ${repo}
        GIT_TAG        ${tag}
    )
    FetchContent_MakeAvailable(${name})
    set(${name}_SOURCE_DIR ${${name}_SOURCE_DIR} PARENT_SCOPE)
endfunction()
fetch_dependency(cpr https://github.com/libcpr/cpr.git 1.11.2)
fetch_dependency(simdjson https://github.com/simdjson/simdjson.git v3.12.3)
fetch_dependency(spdlog https://github.com/gabime/spdlog.git v1.15.2)
fetch_dependency(paddleocr https://github.com/PaddlePaddle/PaddleOCR.git v3.2.0)

FetchContent_GetProperties(paddleocr)
if (paddleocr_POPULATED)
    set(PADDLE_PATCH_FILE ${CMAKE_SOURCE_DIR}/cmake/paddleocr.patch)
    execute_process(
        COMMAND patch -p1 -N --forward --silent -i ${PADDLE_PATCH_FILE}
        WORKING_DIRECTORY ${paddleocr_SOURCE_DIR}
    )
endif()

function(fetch_onnxruntime TAG)
    if(APPLE)
        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
            set(ONNXRUNTIME_DOWNLOAD "onnxruntime-osx-arm64-${TAG}")
        elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64")
            set(ONNXRUNTIME_DOWNLOAD "onnxruntime-osx-x86_64-${TAG}")
        else()
            set(ONNXRUNTIME_DOWNLOAD "onnxruntime-osx-universal2-${TAG}")
        endif()
    elseif(UNIX)
        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
            set(ONNXRUNTIME_DOWNLOAD "onnxruntime-linux-aarch64-${TAG}")
        else()
            set(ONNXRUNTIME_DOWNLOAD "onnxruntime-linux-x64-${TAG}")
        endif()
    endif()

    set(ONNXRUNTIME_DIR ${FETCHCONTENT_BASE_DIR}/onnxruntime)

    if(NOT EXISTS ${ONNXRUNTIME_DIR})
        file(DOWNLOAD https://github.com/microsoft/onnxruntime/releases/download/v${TAG}/${ONNXRUNTIME_DOWNLOAD}.tgz ${FETCHCONTENT_BASE_DIR}/${ONNXRUNTIME_DOWNLOAD}.tgz SHOW_PROGRESS)
        file(ARCHIVE_EXTRACT INPUT ${FETCHCONTENT_BASE_DIR}/${ONNXRUNTIME_DOWNLOAD}.tgz DESTINATION ${FETCHCONTENT_BASE_DIR})
        file(REMOVE ${FETCHCONTENT_BASE_DIR}/${ONNXRUNTIME_DOWNLOAD}.tgz)
        file(RENAME ${FETCHCONTENT_BASE_DIR}/${ONNXRUNTIME_DOWNLOAD} ${ONNXRUNTIME_DIR})
    endif()

    set(ONNXRUNTIME_INCLUDE_DIRS ${ONNXRUNTIME_DIR}/include PARENT_SCOPE)
    set(ONNXRUNTIME_LIB ${ONNXRUNTIME_DIR}/lib)
    find_library(ONNXRUNTIME_LIBRARIES_LOCAL onnxruntime PATHS ${ONNXRUNTIME_LIB} NO_DEFAULT_PATH)
    set(ONNXRUNTIME_LIBRARIES ${ONNXRUNTIME_LIBRARIES_LOCAL} PARENT_SCOPE)
endfunction()
fetch_onnxruntime(1.23.0)

function(fetch_paddle_inference_and_deps)
    if(APPLE)
        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
            set(PADDLE_INFERENCE_DOWNLOAD "MacOS/m1_clang_noavx_accelerate_blas/paddle_inference.tgz")
        elseif(CMAKE_OSX_ARCHITECTURES STREQUAL "x86_64")
            set(PADDLE_INFERENCE_DOWNLOAD "MacOS/x86-64_clang_avx_accelerate_blas/paddle_inference.tgz")
        endif()
    elseif(UNIX)
        set(PADDLE_INFERENCE_DOWNLOAD "Linux/CPU/gcc8.2_avx_mkl/paddle_inference.tgz")
    endif()

    set(PADDLE_INFERENCE_DIR ${FETCHCONTENT_BASE_DIR}/paddle_inference)

    if(NOT EXISTS ${PADDLE_INFERENCE_DIR})
        file(DOWNLOAD https://paddle-inference-lib.bj.bcebos.com/3.0.0/cxx_c/${PADDLE_INFERENCE_DOWNLOAD} ${FETCHCONTENT_BASE_DIR}/paddle_inference.tgz SHOW_PROGRESS)
        file(ARCHIVE_EXTRACT INPUT ${FETCHCONTENT_BASE_DIR}/paddle_inference.tgz DESTINATION ${FETCHCONTENT_BASE_DIR})
        file(REMOVE ${FETCHCONTENT_BASE_DIR}/paddle_inference.tgz)
        file(RENAME ${FETCHCONTENT_BASE_DIR}/paddle_inference_install_dir ${PADDLE_INFERENCE_DIR})
    endif()

    set(PADDLE_INFERENCE_INCLUDE_DIRS ${PADDLE_INFERENCE_DIR}/paddle/include PARENT_SCOPE)
    set(PADDLE_INFERENCE_LIB ${PADDLE_INFERENCE_DIR}/paddle/lib)
    find_library(PADDLE_INFERENCE_LIBRARIES_LOCAL paddle_inference PATHS ${PADDLE_INFERENCE_LIB} NO_DEFAULT_PATH)
    set(PADDLE_INFERENCE_LIBRARIES ${PADDLE_INFERENCE_LIBRARIES_LOCAL} PARENT_SCOPE)
endfunction()
fetch_paddle_inference_and_deps()

function(download_and_decompress url filename decompress_dir)
    if(NOT EXISTS "${filename}" AND NOT EXISTS "${decompress_dir}")
        file(DOWNLOAD ${url} "${filename}.tmp" SHOW_PROGRESS)
        file(RENAME "${filename}.tmp" ${filename})
    endif()
    if(NOT EXISTS ${decompress_dir})
        file(MAKE_DIRECTORY ${decompress_dir})
        execute_process(COMMAND ${CMAKE_COMMAND} -E tar -xf ${filename} WORKING_DIRECTORY ${decompress_dir})
    endif()
endfunction()

set(PACKAGE_LIST clipper_ver6.4.2 nlohmann)
foreach(PKG ${PACKAGE_LIST})
    set(PKG_URL "https://paddle-model-ecology.bj.bcebos.com/paddlex/cpp/libs/${PKG}.tgz")
    set(PKG_TGZ_PATH "${CMAKE_CURRENT_BINARY_DIR}/${PKG}.tgz")
    set(PKG_DST_PATH "${FETCHCONTENT_BASE_DIR}/${PKG}")
    download_and_decompress(${PKG_URL} ${PKG_TGZ_PATH} ${PKG_DST_PATH})
endforeach()
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third_party/clipper_ver6.4.2/cpp)

if(BUILD_TESTS)
    fetch_dependency(googletest https://github.com/google/googletest.git v1.16.0)
    fetch_dependency(benchmark https://github.com/google/benchmark.git v1.9.2)
endif()