// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaItemComponent int32

const (
	MediaItemComponent_METADATA          MediaItemComponent = 0
	MediaItemComponent_PREVIEW_THUMBNAIL MediaItemComponent = 1
	MediaItemComponent_PLACES            MediaItemComponent = 2
	MediaItemComponent_CLASSIFICATION    MediaItemComponent = 3
	MediaItemComponent_FACES             MediaItemComponent = 4
	MediaItemComponent_OCR               MediaItemComponent = 5
	MediaItemComponent_SEARCH            MediaItemComponent = 6
)

// Enum value maps for MediaItemComponent.
var (
	MediaItemComponent_name = map[int32]string{
		0: "METADATA",
		1: "PREVIEW_THUMBNAIL",
		2: "PLACES",
		3: "CLASSIFICATION",
		4: "FACES",
		5: "OCR",
		6: "SEARCH",
	}
	MediaItemComponent_value = map[string]int32{
		"METADATA":          0,
		"PREVIEW_THUMBNAIL": 1,
		"PLACES":            2,
		"CLASSIFICATION":    3,
		"FACES":             4,
		"OCR":               5,
		"SEARCH":            6,
	}
)

func (x MediaItemComponent) Enum() *MediaItemComponent {
	p := new(MediaItemComponent)
	*p = x
	return p
}

func (x MediaItemComponent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaItemComponent) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (MediaItemComponent) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x MediaItemComponent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaItemComponent.Descriptor instead.
func (MediaItemComponent) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        []byte                 `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigResponse) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type MediaItemProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,3,opt,name=mediaItemId,proto3" json:"mediaItemId,omitempty"`
	Components    []MediaItemComponent   `protobuf:"varint,4,rep,packed,name=components,proto3,enum=MediaItemComponent" json:"components,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,5,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemProcessResponse) Reset() {
	*x = MediaItemProcessResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemProcessResponse) ProtoMessage() {}

func (x *MediaItemProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemProcessResponse.ProtoReflect.Descriptor instead.
func (*MediaItemProcessResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *MediaItemProcessResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaItemProcessResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaItemProcessResponse) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *MediaItemProcessResponse) GetComponents() []MediaItemComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *MediaItemProcessResponse) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MediaItemMetadataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MediaItemId     string                 `protobuf:"bytes,2,opt,name=mediaItemId,proto3" json:"mediaItemId,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	MimeType        *string                `protobuf:"bytes,4,opt,name=mimeType,proto3,oneof" json:"mimeType,omitempty"`
	Type            string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Category        string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Width           *int32                 `protobuf:"varint,7,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height          *int32                 `protobuf:"varint,8,opt,name=height,proto3,oneof" json:"height,omitempty"`
	CreationTime    *string                `protobuf:"bytes,9,opt,name=creationTime,proto3,oneof" json:"creationTime,omitempty"`
	CameraMake      *string                `protobuf:"bytes,10,opt,name=cameraMake,proto3,oneof" json:"cameraMake,omitempty"`
	CameraModel     *string                `protobuf:"bytes,11,opt,name=cameraModel,proto3,oneof" json:"cameraModel,omitempty"`
	FocalLength     *string                `protobuf:"bytes,12,opt,name=focalLength,proto3,oneof" json:"focalLength,omitempty"`
	ApertureFNumber *string                `protobuf:"bytes,13,opt,name=apertureFNumber,proto3,oneof" json:"apertureFNumber,omitempty"`
	IsoEquivalent   *string                `protobuf:"bytes,14,opt,name=isoEquivalent,proto3,oneof" json:"isoEquivalent,omitempty"`
	ExposureTime    *string                `protobuf:"bytes,15,opt,name=exposureTime,proto3,oneof" json:"exposureTime,omitempty"`
	Megapixels      *string                `protobuf:"bytes,16,opt,name=megapixels,proto3,oneof" json:"megapixels,omitempty"`
	Fps             *string                `protobuf:"bytes,17,opt,name=fps,proto3,oneof" json:"fps,omitempty"`
	Latitude        *float64               `protobuf:"fixed64,18,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude       *float64               `protobuf:"fixed64,19,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	ExifData        *string                `protobuf:"bytes,20,opt,name=exifData,proto3,oneof" json:"exifData,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaItemMetadataRequest) Reset() {
	*x = MediaItemMetadataRequest{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemMetadataRequest) ProtoMessage() {}

func (x *MediaItemMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemMetadataRequest.ProtoReflect.Descriptor instead.
func (*MediaItemMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *MediaItemMetadataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetMimeType() string {
	if x != nil && x.MimeType != nil {
		return *x.MimeType
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *MediaItemMetadataRequest) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *MediaItemMetadataRequest) GetCreationTime() string {
	if x != nil && x.CreationTime != nil {
		return *x.CreationTime
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetCameraMake() string {
	if x != nil && x.CameraMake != nil {
		return *x.CameraMake
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetCameraModel() string {
	if x != nil && x.CameraModel != nil {
		return *x.CameraModel
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetFocalLength() string {
	if x != nil && x.FocalLength != nil {
		return *x.FocalLength
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetApertureFNumber() string {
	if x != nil && x.ApertureFNumber != nil {
		return *x.ApertureFNumber
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetIsoEquivalent() string {
	if x != nil && x.IsoEquivalent != nil {
		return *x.IsoEquivalent
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetExposureTime() string {
	if x != nil && x.ExposureTime != nil {
		return *x.ExposureTime
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetMegapixels() string {
	if x != nil && x.Megapixels != nil {
		return *x.Megapixels
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetFps() string {
	if x != nil && x.Fps != nil {
		return *x.Fps
	}
	return ""
}

func (x *MediaItemMetadataRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *MediaItemMetadataRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *MediaItemMetadataRequest) GetExifData() string {
	if x != nil && x.ExifData != nil {
		return *x.ExifData
	}
	return ""
}

type MediaItemPreviewThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,2,opt,name=mediaItemId,proto3" json:"mediaItemId,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	SourcePath    *string                `protobuf:"bytes,4,opt,name=sourcePath,proto3,oneof" json:"sourcePath,omitempty"`
	PreviewPath   *string                `protobuf:"bytes,5,opt,name=previewPath,proto3,oneof" json:"previewPath,omitempty"`
	ThumbnailPath *string                `protobuf:"bytes,6,opt,name=thumbnailPath,proto3,oneof" json:"thumbnailPath,omitempty"`
	Placeholder   *string                `protobuf:"bytes,7,opt,name=placeholder,proto3,oneof" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemPreviewThumbnailRequest) Reset() {
	*x = MediaItemPreviewThumbnailRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemPreviewThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemPreviewThumbnailRequest) ProtoMessage() {}

func (x *MediaItemPreviewThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemPreviewThumbnailRequest.ProtoReflect.Descriptor instead.
func (*MediaItemPreviewThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *MediaItemPreviewThumbnailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaItemPreviewThumbnailRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *MediaItemPreviewThumbnailRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MediaItemPreviewThumbnailRequest) GetSourcePath() string {
	if x != nil && x.SourcePath != nil {
		return *x.SourcePath
	}
	return ""
}

func (x *MediaItemPreviewThumbnailRequest) GetPreviewPath() string {
	if x != nil && x.PreviewPath != nil {
		return *x.PreviewPath
	}
	return ""
}

func (x *MediaItemPreviewThumbnailRequest) GetThumbnailPath() string {
	if x != nil && x.ThumbnailPath != nil {
		return *x.ThumbnailPath
	}
	return ""
}

func (x *MediaItemPreviewThumbnailRequest) GetPlaceholder() string {
	if x != nil && x.Placeholder != nil {
		return *x.Placeholder
	}
	return ""
}

type MediaItemPlaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,2,opt,name=mediaItemId,proto3" json:"mediaItemId,omitempty"`
	Postcode      *string                `protobuf:"bytes,3,opt,name=postcode,proto3,oneof" json:"postcode,omitempty"`
	Country       *string                `protobuf:"bytes,4,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Locality      *string                `protobuf:"bytes,5,opt,name=locality,proto3,oneof" json:"locality,omitempty"` // city, town, village, municipality
	Area          *string                `protobuf:"bytes,6,opt,name=area,proto3,oneof" json:"area,omitempty"`         // suburb, road, neighbourhood
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemPlaceRequest) Reset() {
	*x = MediaItemPlaceRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemPlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemPlaceRequest) ProtoMessage() {}

func (x *MediaItemPlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemPlaceRequest.ProtoReflect.Descriptor instead.
func (*MediaItemPlaceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *MediaItemPlaceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaItemPlaceRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *MediaItemPlaceRequest) GetPostcode() string {
	if x != nil && x.Postcode != nil {
		return *x.Postcode
	}
	return ""
}

func (x *MediaItemPlaceRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *MediaItemPlaceRequest) GetLocality() string {
	if x != nil && x.Locality != nil {
		return *x.Locality
	}
	return ""
}

func (x *MediaItemPlaceRequest) GetArea() string {
	if x != nil && x.Area != nil {
		return *x.Area
	}
	return ""
}

type MediaItemThingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,2,opt,name=mediaItemId,proto3" json:"mediaItemId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemThingRequest) Reset() {
	*x = MediaItemThingRequest{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemThingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemThingRequest) ProtoMessage() {}

func (x *MediaItemThingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemThingRequest.ProtoReflect.Descriptor instead.
func (*MediaItemThingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *MediaItemThingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaItemThingRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *MediaItemThingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MediaItemEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemEmbedding) Reset() {
	*x = MediaItemEmbedding{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemEmbedding) ProtoMessage() {}

func (x *MediaItemEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemEmbedding.ProtoReflect.Descriptor instead.
func (*MediaItemEmbedding) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *MediaItemEmbedding) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type MediaItemFacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,2,opt,name=mediaItemId,proto3" json:"mediaItemId,omitempty"`
	Embeddings    []*MediaItemEmbedding  `protobuf:"bytes,3,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	Thumbnails    []string               `protobuf:"bytes,4,rep,name=thumbnails,proto3" json:"thumbnails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemFacesRequest) Reset() {
	*x = MediaItemFacesRequest{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemFacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemFacesRequest) ProtoMessage() {}

func (x *MediaItemFacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemFacesRequest.ProtoReflect.Descriptor instead.
func (*MediaItemFacesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *MediaItemFacesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaItemFacesRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *MediaItemFacesRequest) GetEmbeddings() []*MediaItemEmbedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *MediaItemFacesRequest) GetThumbnails() []string {
	if x != nil {
		return x.Thumbnails
	}
	return nil
}

type MediaItemFinalResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,3,opt,name=mediaItemId,proto3" json:"mediaItemId,omitempty"`
	Keywords      string                 `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Embeddings    []*MediaItemEmbedding  `protobuf:"bytes,5,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemFinalResultRequest) Reset() {
	*x = MediaItemFinalResultRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemFinalResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemFinalResultRequest) ProtoMessage() {}

func (x *MediaItemFinalResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemFinalResultRequest.ProtoReflect.Descriptor instead.
func (*MediaItemFinalResultRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *MediaItemFinalResultRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaItemFinalResultRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaItemFinalResultRequest) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *MediaItemFinalResultRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *MediaItemFinalResultRequest) GetEmbeddings() []*MediaItemEmbedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type MediaItemFaceEmbeddingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemFaceEmbeddingsRequest) Reset() {
	*x = MediaItemFaceEmbeddingsRequest{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemFaceEmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemFaceEmbeddingsRequest) ProtoMessage() {}

func (x *MediaItemFaceEmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemFaceEmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*MediaItemFaceEmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *MediaItemFaceEmbeddingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MediaItemFaceEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaItemId   string                 `protobuf:"bytes,2,opt,name=mediaItemId,proto3" json:"mediaItemId,omitempty"`
	PeopleId      string                 `protobuf:"bytes,3,opt,name=peopleId,proto3" json:"peopleId,omitempty"`
	Embedding     *MediaItemEmbedding    `protobuf:"bytes,4,opt,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemFaceEmbedding) Reset() {
	*x = MediaItemFaceEmbedding{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemFaceEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemFaceEmbedding) ProtoMessage() {}

func (x *MediaItemFaceEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemFaceEmbedding.ProtoReflect.Descriptor instead.
func (*MediaItemFaceEmbedding) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *MediaItemFaceEmbedding) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaItemFaceEmbedding) GetMediaItemId() string {
	if x != nil {
		return x.MediaItemId
	}
	return ""
}

func (x *MediaItemFaceEmbedding) GetPeopleId() string {
	if x != nil {
		return x.PeopleId
	}
	return ""
}

func (x *MediaItemFaceEmbedding) GetEmbedding() *MediaItemEmbedding {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type MediaItemFaceEmbeddingsResponse struct {
	state                   protoimpl.MessageState    `protogen:"open.v1"`
	MediaItemFaceEmbeddings []*MediaItemFaceEmbedding `protobuf:"bytes,1,rep,name=mediaItemFaceEmbeddings,proto3" json:"mediaItemFaceEmbeddings,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MediaItemFaceEmbeddingsResponse) Reset() {
	*x = MediaItemFaceEmbeddingsResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemFaceEmbeddingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemFaceEmbeddingsResponse) ProtoMessage() {}

func (x *MediaItemFaceEmbeddingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemFaceEmbeddingsResponse.ProtoReflect.Descriptor instead.
func (*MediaItemFaceEmbeddingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *MediaItemFaceEmbeddingsResponse) GetMediaItemFaceEmbeddings() []*MediaItemFaceEmbedding {
	if x != nil {
		return x.MediaItemFaceEmbeddings
	}
	return nil
}

type UsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []string               `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *UsersResponse) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

type MediaItemFacePeople struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacePeople    map[string]string      `protobuf:"bytes,1,rep,name=facePeople,proto3" json:"facePeople,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItemFacePeople) Reset() {
	*x = MediaItemFacePeople{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemFacePeople) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemFacePeople) ProtoMessage() {}

func (x *MediaItemFacePeople) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemFacePeople.ProtoReflect.Descriptor instead.
func (*MediaItemFacePeople) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *MediaItemFacePeople) GetFacePeople() map[string]string {
	if x != nil {
		return x.FacePeople
	}
	return nil
}

type MediaItemPeopleRequest struct {
	state               protoimpl.MessageState          `protogen:"open.v1"`
	UserId              string                          `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	MediaItemFacePeople map[string]*MediaItemFacePeople `protobuf:"bytes,2,rep,name=mediaItemFacePeople,proto3" json:"mediaItemFacePeople,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MediaItemPeopleRequest) Reset() {
	*x = MediaItemPeopleRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItemPeopleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItemPeopleRequest) ProtoMessage() {}

func (x *MediaItemPeopleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItemPeopleRequest.ProtoReflect.Descriptor instead.
func (*MediaItemPeopleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *MediaItemPeopleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MediaItemPeopleRequest) GetMediaItemFacePeople() map[string]*MediaItemFacePeople {
	if x != nil {
		return x.MediaItemFacePeople
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x1a\x1bgoogle/protobuf/empty.proto\"(\n" +
	"\x0eConfigResponse\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\x97\x02\n" +
	"\x18MediaItemProcessResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12 \n" +
	"\vmediaItemId\x18\x03 \x01(\tR\vmediaItemId\x123\n" +
	"\n" +
	"components\x18\x04 \x03(\x0e2\x13.MediaItemComponentR\n" +
	"components\x12@\n" +
	"\apayload\x18\x05 \x03(\v2&.MediaItemProcessResponse.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\a\n" +
	"\x18MediaItemMetadataRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vmediaItemId\x18\x02 \x01(\tR\vmediaItemId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\bmimeType\x18\x04 \x01(\tH\x00R\bmimeType\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x19\n" +
	"\x05width\x18\a \x01(\x05H\x01R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\b \x01(\x05H\x02R\x06height\x88\x01\x01\x12'\n" +
	"\fcreationTime\x18\t \x01(\tH\x03R\fcreationTime\x88\x01\x01\x12#\n" +
	"\n" +
	"cameraMake\x18\n" +
	" \x01(\tH\x04R\n" +
	"cameraMake\x88\x01\x01\x12%\n" +
	"\vcameraModel\x18\v \x01(\tH\x05R\vcameraModel\x88\x01\x01\x12%\n" +
	"\vfocalLength\x18\f \x01(\tH\x06R\vfocalLength\x88\x01\x01\x12-\n" +
	"\x0fapertureFNumber\x18\r \x01(\tH\aR\x0fapertureFNumber\x88\x01\x01\x12)\n" +
	"\risoEquivalent\x18\x0e \x01(\tH\bR\risoEquivalent\x88\x01\x01\x12'\n" +
	"\fexposureTime\x18\x0f \x01(\tH\tR\fexposureTime\x88\x01\x01\x12#\n" +
	"\n" +
	"megapixels\x18\x10 \x01(\tH\n" +
	"R\n" +
	"megapixels\x88\x01\x01\x12\x15\n" +
	"\x03fps\x18\x11 \x01(\tH\vR\x03fps\x88\x01\x01\x12\x1f\n" +
	"\blatitude\x18\x12 \x01(\x01H\fR\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x13 \x01(\x01H\rR\tlongitude\x88\x01\x01\x12\x1f\n" +
	"\bexifData\x18\x14 \x01(\tH\x0eR\bexifData\x88\x01\x01B\v\n" +
	"\t_mimeTypeB\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\x0f\n" +
	"\r_creationTimeB\r\n" +
	"\v_cameraMakeB\x0e\n" +
	"\f_cameraModelB\x0e\n" +
	"\f_focalLengthB\x12\n" +
	"\x10_apertureFNumberB\x10\n" +
	"\x0e_isoEquivalentB\x0f\n" +
	"\r_exposureTimeB\r\n" +
	"\v_megapixelsB\x06\n" +
	"\x04_fpsB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\v\n" +
	"\t_exifData\"\xd3\x02\n" +
	" MediaItemPreviewThumbnailRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vmediaItemId\x18\x02 \x01(\tR\vmediaItemId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\n" +
	"sourcePath\x18\x04 \x01(\tH\x00R\n" +
	"sourcePath\x88\x01\x01\x12%\n" +
	"\vpreviewPath\x18\x05 \x01(\tH\x01R\vpreviewPath\x88\x01\x01\x12)\n" +
	"\rthumbnailPath\x18\x06 \x01(\tH\x02R\rthumbnailPath\x88\x01\x01\x12%\n" +
	"\vplaceholder\x18\a \x01(\tH\x03R\vplaceholder\x88\x01\x01B\r\n" +
	"\v_sourcePathB\x0e\n" +
	"\f_previewPathB\x10\n" +
	"\x0e_thumbnailPathB\x0e\n" +
	"\f_placeholder\"\xfa\x01\n" +
	"\x15MediaItemPlaceRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vmediaItemId\x18\x02 \x01(\tR\vmediaItemId\x12\x1f\n" +
	"\bpostcode\x18\x03 \x01(\tH\x00R\bpostcode\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\x04 \x01(\tH\x01R\acountry\x88\x01\x01\x12\x1f\n" +
	"\blocality\x18\x05 \x01(\tH\x02R\blocality\x88\x01\x01\x12\x17\n" +
	"\x04area\x18\x06 \x01(\tH\x03R\x04area\x88\x01\x01B\v\n" +
	"\t_postcodeB\n" +
	"\n" +
	"\b_countryB\v\n" +
	"\t_localityB\a\n" +
	"\x05_area\"e\n" +
	"\x15MediaItemThingRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vmediaItemId\x18\x02 \x01(\tR\vmediaItemId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"2\n" +
	"\x12MediaItemEmbedding\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\"\xa6\x01\n" +
	"\x15MediaItemFacesRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vmediaItemId\x18\x02 \x01(\tR\vmediaItemId\x123\n" +
	"\n" +
	"embeddings\x18\x03 \x03(\v2\x13.MediaItemEmbeddingR\n" +
	"embeddings\x12\x1e\n" +
	"\n" +
	"thumbnails\x18\x04 \x03(\tR\n" +
	"thumbnails\"\xb8\x01\n" +
	"\x1bMediaItemFinalResultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12 \n" +
	"\vmediaItemId\x18\x03 \x01(\tR\vmediaItemId\x12\x1a\n" +
	"\bkeywords\x18\x04 \x01(\tR\bkeywords\x123\n" +
	"\n" +
	"embeddings\x18\x05 \x03(\v2\x13.MediaItemEmbeddingR\n" +
	"embeddings\"8\n" +
	"\x1eMediaItemFaceEmbeddingsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x99\x01\n" +
	"\x16MediaItemFaceEmbedding\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vmediaItemId\x18\x02 \x01(\tR\vmediaItemId\x12\x1a\n" +
	"\bpeopleId\x18\x03 \x01(\tR\bpeopleId\x121\n" +
	"\tembedding\x18\x04 \x01(\v2\x13.MediaItemEmbeddingR\tembedding\"t\n" +
	"\x1fMediaItemFaceEmbeddingsResponse\x12Q\n" +
	"\x17mediaItemFaceEmbeddings\x18\x01 \x03(\v2\x17.MediaItemFaceEmbeddingR\x17mediaItemFaceEmbeddings\"%\n" +
	"\rUsersResponse\x12\x14\n" +
	"\x05users\x18\x01 \x03(\tR\x05users\"\x9a\x01\n" +
	"\x13MediaItemFacePeople\x12D\n" +
	"\n" +
	"facePeople\x18\x01 \x03(\v2$.MediaItemFacePeople.FacePeopleEntryR\n" +
	"facePeople\x1a=\n" +
	"\x0fFacePeopleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x01\n" +
	"\x16MediaItemPeopleRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12b\n" +
	"\x13mediaItemFacePeople\x18\x02 \x03(\v20.MediaItemPeopleRequest.MediaItemFacePeopleEntryR\x13mediaItemFacePeople\x1a\\\n" +
	"\x18MediaItemFacePeopleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.MediaItemFacePeopleR\x05value:\x028\x01*y\n" +
	"\x12MediaItemComponent\x12\f\n" +
	"\bMETADATA\x10\x00\x12\x15\n" +
	"\x11PREVIEW_THUMBNAIL\x10\x01\x12\n" +
	"\n" +
	"\x06PLACES\x10\x02\x12\x12\n" +
	"\x0eCLASSIFICATION\x10\x03\x12\t\n" +
	"\x05FACES\x10\x04\x12\a\n" +
	"\x03OCR\x10\x05\x12\n" +
	"\n" +
	"\x06SEARCH\x10\x062\xca\x06\n" +
	"\x03API\x12<\n" +
	"\x0fGetWorkerConfig\x12\x16.google.protobuf.Empty\x1a\x0f.ConfigResponse\"\x00\x12J\n" +
	"\x13GetMediaItemProcess\x12\x16.google.protobuf.Empty\x1a\x19.MediaItemProcessResponse\"\x00\x12a\n" +
	"\x1aGetMediaItemFaceEmbeddings\x12\x1f.MediaItemFaceEmbeddingsRequest\x1a .MediaItemFaceEmbeddingsResponse\"\x00\x124\n" +
	"\bGetUsers\x12\x16.google.protobuf.Empty\x1a\x0e.UsersResponse\"\x00\x12L\n" +
	"\x15SaveMediaItemMetadata\x12\x19.MediaItemMetadataRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\\\n" +
	"\x1dSaveMediaItemPreviewThumbnail\x12!.MediaItemPreviewThumbnailRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\x12SaveMediaItemPlace\x12\x16.MediaItemPlaceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\x12SaveMediaItemThing\x12\x16.MediaItemThingRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\x12SaveMediaItemFaces\x12\x16.MediaItemFacesRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x13SaveMediaItemPeople\x12\x17.MediaItemPeopleRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\x18SaveMediaItemFinalResult\x12\x1c.MediaItemFinalResultRequest\x1a\x16.google.protobuf.Empty\"\x00B\x06Z\x04api/b\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_goTypes = []any{
	(MediaItemComponent)(0),                  // 0: MediaItemComponent
	(*ConfigResponse)(nil),                   // 1: ConfigResponse
	(*MediaItemProcessResponse)(nil),         // 2: MediaItemProcessResponse
	(*MediaItemMetadataRequest)(nil),         // 3: MediaItemMetadataRequest
	(*MediaItemPreviewThumbnailRequest)(nil), // 4: MediaItemPreviewThumbnailRequest
	(*MediaItemPlaceRequest)(nil),            // 5: MediaItemPlaceRequest
	(*MediaItemThingRequest)(nil),            // 6: MediaItemThingRequest
	(*MediaItemEmbedding)(nil),               // 7: MediaItemEmbedding
	(*MediaItemFacesRequest)(nil),            // 8: MediaItemFacesRequest
	(*MediaItemFinalResultRequest)(nil),      // 9: MediaItemFinalResultRequest
	(*MediaItemFaceEmbeddingsRequest)(nil),   // 10: MediaItemFaceEmbeddingsRequest
	(*MediaItemFaceEmbedding)(nil),           // 11: MediaItemFaceEmbedding
	(*MediaItemFaceEmbeddingsResponse)(nil),  // 12: MediaItemFaceEmbeddingsResponse
	(*UsersResponse)(nil),                    // 13: UsersResponse
	(*MediaItemFacePeople)(nil),              // 14: MediaItemFacePeople
	(*MediaItemPeopleRequest)(nil),           // 15: MediaItemPeopleRequest
	nil,                                      // 16: MediaItemProcessResponse.PayloadEntry
	nil,                                      // 17: MediaItemFacePeople.FacePeopleEntry
	nil,                                      // 18: MediaItemPeopleRequest.MediaItemFacePeopleEntry
	(*emptypb.Empty)(nil),                    // 19: google.protobuf.Empty
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: MediaItemProcessResponse.components:type_name -> MediaItemComponent
	16, // 1: MediaItemProcessResponse.payload:type_name -> MediaItemProcessResponse.PayloadEntry
	7,  // 2: MediaItemFacesRequest.embeddings:type_name -> MediaItemEmbedding
	7,  // 3: MediaItemFinalResultRequest.embeddings:type_name -> MediaItemEmbedding
	7,  // 4: MediaItemFaceEmbedding.embedding:type_name -> MediaItemEmbedding
	11, // 5: MediaItemFaceEmbeddingsResponse.mediaItemFaceEmbeddings:type_name -> MediaItemFaceEmbedding
	17, // 6: MediaItemFacePeople.facePeople:type_name -> MediaItemFacePeople.FacePeopleEntry
	18, // 7: MediaItemPeopleRequest.mediaItemFacePeople:type_name -> MediaItemPeopleRequest.MediaItemFacePeopleEntry
	14, // 8: MediaItemPeopleRequest.MediaItemFacePeopleEntry.value:type_name -> MediaItemFacePeople
	19, // 9: API.GetWorkerConfig:input_type -> google.protobuf.Empty
	19, // 10: API.GetMediaItemProcess:input_type -> google.protobuf.Empty
	10, // 11: API.GetMediaItemFaceEmbeddings:input_type -> MediaItemFaceEmbeddingsRequest
	19, // 12: API.GetUsers:input_type -> google.protobuf.Empty
	3,  // 13: API.SaveMediaItemMetadata:input_type -> MediaItemMetadataRequest
	4,  // 14: API.SaveMediaItemPreviewThumbnail:input_type -> MediaItemPreviewThumbnailRequest
	5,  // 15: API.SaveMediaItemPlace:input_type -> MediaItemPlaceRequest
	6,  // 16: API.SaveMediaItemThing:input_type -> MediaItemThingRequest
	8,  // 17: API.SaveMediaItemFaces:input_type -> MediaItemFacesRequest
	15, // 18: API.SaveMediaItemPeople:input_type -> MediaItemPeopleRequest
	9,  // 19: API.SaveMediaItemFinalResult:input_type -> MediaItemFinalResultRequest
	1,  // 20: API.GetWorkerConfig:output_type -> ConfigResponse
	2,  // 21: API.GetMediaItemProcess:output_type -> MediaItemProcessResponse
	12, // 22: API.GetMediaItemFaceEmbeddings:output_type -> MediaItemFaceEmbeddingsResponse
	13, // 23: API.GetUsers:output_type -> UsersResponse
	19, // 24: API.SaveMediaItemMetadata:output_type -> google.protobuf.Empty
	19, // 25: API.SaveMediaItemPreviewThumbnail:output_type -> google.protobuf.Empty
	19, // 26: API.SaveMediaItemPlace:output_type -> google.protobuf.Empty
	19, // 27: API.SaveMediaItemThing:output_type -> google.protobuf.Empty
	19, // 28: API.SaveMediaItemFaces:output_type -> google.protobuf.Empty
	19, // 29: API.SaveMediaItemPeople:output_type -> google.protobuf.Empty
	19, // 30: API.SaveMediaItemFinalResult:output_type -> google.protobuf.Empty
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
