# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from src.protos import api_pb2 as src_dot_protos_dot_api__pb2


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWorkerConfig = channel.unary_unary(
                '/API/GetWorkerConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=src_dot_protos_dot_api__pb2.ConfigResponse.FromString,
                )
        self.GetMediaItemFaceEmbeddings = channel.unary_unary(
                '/API/GetMediaItemFaceEmbeddings',
                request_serializer=src_dot_protos_dot_api__pb2.MediaItemFaceEmbeddingsRequest.SerializeToString,
                response_deserializer=src_dot_protos_dot_api__pb2.MediaItemFaceEmbeddingsResponse.FromString,
                )
        self.SaveMediaItemMetadata = channel.unary_unary(
                '/API/SaveMediaItemMetadata',
                request_serializer=src_dot_protos_dot_api__pb2.MediaItemMetadataRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveMediaItemPlace = channel.unary_unary(
                '/API/SaveMediaItemPlace',
                request_serializer=src_dot_protos_dot_api__pb2.MediaItemPlaceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveMediaItemThing = channel.unary_unary(
                '/API/SaveMediaItemThing',
                request_serializer=src_dot_protos_dot_api__pb2.MediaItemThingRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveMediaItemFaces = channel.unary_unary(
                '/API/SaveMediaItemFaces',
                request_serializer=src_dot_protos_dot_api__pb2.MediaItemFacesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveMediaItemPeople = channel.unary_unary(
                '/API/SaveMediaItemPeople',
                request_serializer=src_dot_protos_dot_api__pb2.MediaItemPeopleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SaveMediaItemFinalResult = channel.unary_unary(
                '/API/SaveMediaItemFinalResult',
                request_serializer=src_dot_protos_dot_api__pb2.MediaItemFinalResultRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWorkerConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMediaItemFaceEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMediaItemMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMediaItemPlace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMediaItemThing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMediaItemFaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMediaItemPeople(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMediaItemFinalResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWorkerConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkerConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=src_dot_protos_dot_api__pb2.ConfigResponse.SerializeToString,
            ),
            'GetMediaItemFaceEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMediaItemFaceEmbeddings,
                    request_deserializer=src_dot_protos_dot_api__pb2.MediaItemFaceEmbeddingsRequest.FromString,
                    response_serializer=src_dot_protos_dot_api__pb2.MediaItemFaceEmbeddingsResponse.SerializeToString,
            ),
            'SaveMediaItemMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMediaItemMetadata,
                    request_deserializer=src_dot_protos_dot_api__pb2.MediaItemMetadataRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveMediaItemPlace': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMediaItemPlace,
                    request_deserializer=src_dot_protos_dot_api__pb2.MediaItemPlaceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveMediaItemThing': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMediaItemThing,
                    request_deserializer=src_dot_protos_dot_api__pb2.MediaItemThingRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveMediaItemFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMediaItemFaces,
                    request_deserializer=src_dot_protos_dot_api__pb2.MediaItemFacesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveMediaItemPeople': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMediaItemPeople,
                    request_deserializer=src_dot_protos_dot_api__pb2.MediaItemPeopleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SaveMediaItemFinalResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMediaItemFinalResult,
                    request_deserializer=src_dot_protos_dot_api__pb2.MediaItemFinalResultRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWorkerConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/GetWorkerConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            src_dot_protos_dot_api__pb2.ConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMediaItemFaceEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/GetMediaItemFaceEmbeddings',
            src_dot_protos_dot_api__pb2.MediaItemFaceEmbeddingsRequest.SerializeToString,
            src_dot_protos_dot_api__pb2.MediaItemFaceEmbeddingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveMediaItemMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/SaveMediaItemMetadata',
            src_dot_protos_dot_api__pb2.MediaItemMetadataRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveMediaItemPlace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/SaveMediaItemPlace',
            src_dot_protos_dot_api__pb2.MediaItemPlaceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveMediaItemThing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/SaveMediaItemThing',
            src_dot_protos_dot_api__pb2.MediaItemThingRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveMediaItemFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/SaveMediaItemFaces',
            src_dot_protos_dot_api__pb2.MediaItemFacesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveMediaItemPeople(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/SaveMediaItemPeople',
            src_dot_protos_dot_api__pb2.MediaItemPeopleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveMediaItemFinalResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/API/SaveMediaItemFinalResult',
            src_dot_protos_dot_api__pb2.MediaItemFinalResultRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
