# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/protos/worker.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17src/protos/worker.proto\"\xd8\x01\n\x17MediaItemProcessRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x10\n\x08\x66ilePath\x18\x03 \x01(\t\x12\'\n\ncomponents\x18\x04 \x03(\x0e\x32\x13.MediaItemComponent\x12\x36\n\x07payload\x18\x05 \x03(\x0b\x32%.MediaItemProcessRequest.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x18MediaItemProcessResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"(\n\x18GenerateEmbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\".\n\x19GenerateEmbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02*y\n\x12MediaItemComponent\x12\x0c\n\x08METADATA\x10\x00\x12\x15\n\x11PREVIEW_THUMBNAIL\x10\x01\x12\n\n\x06PLACES\x10\x02\x12\x12\n\x0e\x43LASSIFICATION\x10\x03\x12\t\n\x05\x46\x41\x43\x45S\x10\x04\x12\x07\n\x03OCR\x10\x05\x12\n\n\x06SEARCH\x10\x06\x32\xa1\x01\n\x06Worker\x12I\n\x10MediaItemProcess\x12\x18.MediaItemProcessRequest\x1a\x19.MediaItemProcessResponse\"\x00\x12L\n\x11GenerateEmbedding\x12\x19.GenerateEmbeddingRequest\x1a\x1a.GenerateEmbeddingResponse\"\x00\x42\tZ\x07worker/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.protos.worker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007worker/'
  _globals['_MEDIAITEMPROCESSREQUEST_PAYLOADENTRY']._options = None
  _globals['_MEDIAITEMPROCESSREQUEST_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_MEDIAITEMCOMPONENT']._serialized_start=376
  _globals['_MEDIAITEMCOMPONENT']._serialized_end=497
  _globals['_MEDIAITEMPROCESSREQUEST']._serialized_start=28
  _globals['_MEDIAITEMPROCESSREQUEST']._serialized_end=244
  _globals['_MEDIAITEMPROCESSREQUEST_PAYLOADENTRY']._serialized_start=198
  _globals['_MEDIAITEMPROCESSREQUEST_PAYLOADENTRY']._serialized_end=244
  _globals['_MEDIAITEMPROCESSRESPONSE']._serialized_start=246
  _globals['_MEDIAITEMPROCESSRESPONSE']._serialized_end=284
  _globals['_GENERATEEMBEDDINGREQUEST']._serialized_start=286
  _globals['_GENERATEEMBEDDINGREQUEST']._serialized_end=326
  _globals['_GENERATEEMBEDDINGRESPONSE']._serialized_start=328
  _globals['_GENERATEEMBEDDINGRESPONSE']._serialized_end=374
  _globals['_WORKER']._serialized_start=500
  _globals['_WORKER']._serialized_end=661
# @@protoc_insertion_point(module_scope)
