# fly.toml file generated for carousel-worker on 2022-09-30T22:30:52+05:30

app = "carousel-worker"

[[services]]
  internal_port = 15002
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 15002

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"