# this is a reference toml file for deployment of API server on Fly

app = "?"

[build]
  image = "?"

[env]
  CAROUSEL_WORKER_HOST = "?"
  CAROUSEL_DATABASE_HOST = "?"
  CAROUSEL_DATABASE_USERNAME = "?"
  CAROUSEL_DATABASE_PASSWORD = "?"
  CAROUSEL_DATABASE_NAME = "?"

[[services]]
  internal_port = 5001
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 15
    soft_limit = 10
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "2s"

[[services]]
  internal_port = 15001
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 15
    soft_limit = 10
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 15001

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "2s"