# this is a reference toml file for deployment of Worker server on Fly

app = "?"

[[services]]
  internal_port = 15002
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 15002

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"