# this is a reference toml file for deployment of Worker server on Fly

app = "?"

[build]
  image = "?"

[[services]]
  internal_port = 15002
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 15
    soft_limit = 10
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 15002

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "2s"