run:
  tests: false
linters:
  enable-all: true
  disable:
    - nlreturn
    - nosprintfhostport
    - wsl
    - wrapcheck
    - exhaustivestruct
    - exhaustruct
    - gci
    - dupl
    - goerr113