run:
  timeout: 2m
  tests: false
linters:
  enable-all: true
  disable:
    - nlreturn
    - nosprintfhostport
    - wsl
    - wrapcheck
    - exhaustivestruct
    - exhaustruct
    - gci
    - dupl
    - goerr113
    - tagalign
    - depguard
    - interfacer
    - protogetter
linters-settings:
  lll:
    line-length: 180
