version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - dupl
    - protogetter
    - tagalign
    - wrapcheck
    - wsl_v5
    - noinlineerr
    - wsl
    - funlen
    - unqueryvet
  settings:
    lll:
      line-length: 180
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
