# fly.toml file generated for carousel-api on 2022-09-30T22:34:01+05:30

app = "carousel-api"

[env]
  CAROUSEL_WORKER_HOST = "carousel-worker.fly.dev"
  CAROUSEL_DATABASE_HOST = "lucky.db.elephantsql.com"
  CAROUSEL_DATABASE_USERNAME = "ztrpncqo"
  CAROUSEL_DATABASE_PASSWORD = "RMBXZI0DqbtOIOLfVMZFk_M6qFfrljOz"
  CAROUSEL_DATABASE_NAME = "ztrpncqo"

[[services]]
  internal_port = 5001
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"

[[services]]
  internal_port = 15001
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 15001

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"