name: Pensieve API CI
on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - run: go version
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - run: make build