name: Pensieve API CI
on:
  push:
    branches:    
      - master
    paths:
      - api/**
  pull_request:
    branches:
      - master
    paths:
      - api/**
  release:
    types: [published]
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - run: go version
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: api
      - run: make build
      - run: make cover
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: api
  deploy:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    name: Fly Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          args: latest
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}