name: Smriti ML Models
on:
  release:
    types: [published]
jobs:
  publish:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    name: Release ML Models
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ml
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Python Version
        run: python -c "import sys; print(sys.version)"
      - name: Install Dependencies
        run: make install
      