name: Smriti ML Models
on:
  release:
    types: [published]
jobs:
  publish:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    name: Release ML Models
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    defaults:
      run:
        working-directory: ./ml
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'
      - name: Python Version
        run: python -c "import sys; print(sys.version)"
      - name: Install Dependencies
        run: make install
      - name: Create models
        run: |
          make all
          zip -r models.zip classification/*.pt faces/*.pt ocr/cls_onnx ocr/det_onnx ocr/rec_onnx search/*.pt search/search_processor search/search_tokenizer
      - name: Create release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ml/models.zip
      