name: Smriti Worker CI
on:
  push:
    branches:    
      - master
    paths:
      - worker/**
      - .github/workflows/worker.yaml
  pull_request:
    branches:
      - master
    paths:
      - worker/**
      - .github/workflows/worker.yaml
  release:
    types: [published]
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'
      - name: Python Version
        run: python -c "import sys; print(sys.version)"
      - name: Install Dependencies
        run: make install
      - name: Run Lint
        run: |
          pip install pylint==3.3.4
          make lint
      - name: Run Test & Cover
        run: |
          sudo apt-get install -y libimage-exiftool-perl exiftool libraw-dev
          make test-install
          make cover
      - name: Publish Coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: worker
          files: worker/coverage.xml
  publish:
    if: ${{ (github.event_name == 'release' && github.event.action == 'published') || github.ref == 'refs/heads/master' }}
    needs: ci
    name: Publish Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: worker
          file: ./worker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          build-args: |
            GITSHA=${{ github.sha }}
            VERSION=${ github.ref_name }}
          tags: smritihq/worker:${{ github.ref_name }}