name: Pensieve Worker CI
on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -c "import sys; print(sys.version)"
      - run: pip install -r requirements.txt
      - run: |
          pip install pylint
          pylint main.py