name: Pensieve Worker CI
on:
  push:
    branches:    
      - master
    paths:
      - worker/**
  pull_request:
    branches:
      - master
    paths:
      - worker/**
  release:
    types: [published]
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -c "import sys; print(sys.version)"
      - run: pip install -r requirements.txt
      - run: |
          pip install pylint
          make lint
      - run: |
          pip install pytest pytest-cov requests-mock
          make cover
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: worker
  publish:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: ci
    name: Publish Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build . --file Dockerfile --tag prabhuomkar/pensieve-worker:${GITHUB_REF:11}
      - run: docker push prabhuomkar/pensieve-worker:${GITHUB_REF:11}
  deploy:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: publish
    name: Fly Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          args: latest
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}