name: Pensieve Worker CI
on:
  push:
    branches:    
      - master
    paths:
      - worker/**
  pull_request:
    branches:
      - master
    paths:
      - worker/**
  release:
    types: [published]
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -c "import sys; print(sys.version)"
      - run: pip install -r requirements.txt
      - run: |
          pip install pylint
          make lint
  deploy:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    name: Fly Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          args: latest
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}