name: Carousel Worker CI
on:
  push:
    branches:    
      - master
    paths:
      - worker/**
  pull_request:
    branches:
      - master
    paths:
      - worker/**
  release:
    types: [published]
jobs:
  ci:
    name: Integration Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Python Version
        run: python -c "import sys; print(sys.version)"
      - name: Install Dependencies
        run: make install
      - name: Run Lint
        run: |
          pip install pylint
          make lint
      - name: Run Test & Cover
        run: |
          sudo apt-get install -y libimage-exiftool-perl exiftool libraw-dev
          make test-install
          make cover
      - name: Publish Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: worker
          files: worker/coverage.xml
  publish:
    if: ${{ (github.event_name == 'release' && github.event.action == 'published') || github.ref == 'refs/heads/master' }}
    needs: ci
    name: Publish Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: docker build . --file Dockerfile --tag carouselhq/worker:${GITHUB_REF_NAME}
      - name: Docker Publish
        run: docker push carouselhq/worker:${GITHUB_REF_NAME}
  deploy:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: publish
    name: Fly Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/deployments/fly
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          args: latest
      - run: |
          sed -i -e '/app =/ s/= .*/= "carousel-worker"/' worker.toml
          sed -i -e '/image =/ s/= .*/= "carouselhq\/worker:'$GITHUB_REF_NAME'"/' worker.toml
      - run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}